from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path
from tempfile import TemporaryDirectory


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from content_agent_os.runner import run_workflow  # noqa: E402
from content_agent_os.workflow import load_workflow  # noqa: E402


VIDEO_PLATFORMS = ["douyin", "shipinhao", "bilibili"]


def fail(message: str) -> None:
    print(f"Phase 4 asset pipeline validation failed: {message}", file=sys.stderr)
    raise SystemExit(1)


def expect(condition: bool, message: str) -> None:
    if not condition:
        fail(message)


def load_json(path: Path) -> dict:
    if not path.exists():
        fail(f"missing JSON file: {path}")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        fail(f"invalid JSON file {path}: {exc}")


def validate_workflow_outputs() -> None:
    workflow = load_workflow(ROOT / "workflows/one_topic_multi_platform.yaml")
    steps = {step.id: step for step in workflow.steps}
    visual_assets = steps.get("visual_assets")
    expect(visual_assets is not None, "workflow missing visual_assets step")
    expected = {
        "asset_plan.json",
        "cover_prompts.md",
        "assets/asset_generation_tasks.json",
        "assets/media_asset_manifest.json",
        "assets/asset_ingest_guide.md",
    }
    expect(expected.issubset(set(visual_assets.outputs)), "visual_assets missing asset pipeline outputs")


def validate_asset_pipeline_run() -> None:
    with TemporaryDirectory() as tmp:
        output_root = Path(tmp) / "runs"
        run_dir = run_workflow(
            workflow_path=ROOT / "workflows/one_topic_multi_platform.yaml",
            topic="Phase 4 素材生成导入层验收",
            platforms=VIDEO_PLATFORMS,
            output_root=output_root,
        )

        workflow_run = load_json(run_dir / "workflow_run.json")
        expect(workflow_run.get("status") == "DONE", "workflow should finish")

        asset_tasks = load_json(run_dir / "assets/asset_generation_tasks.json")
        expect(asset_tasks.get("schema_version") == "phase4.asset_generation_tasks.v1", "asset tasks schema version mismatch")
        expect(asset_tasks.get("generated_by") == "asset-agent", "asset tasks must be generated by asset-agent")
        boundary = asset_tasks.get("execution_boundary", {})
        for key in ["asset_generation", "asset_download", "asset_import"]:
            expect(boundary.get(key) == "not_performed", f"asset task boundary must mark {key} as not_performed")
        expect(boundary.get("rights_clearance") == "human_review_required", "rights clearance must require human review")

        tasks = asset_tasks.get("tasks", [])
        expect(isinstance(tasks, list) and tasks, "asset tasks must be non-empty")
        task_counts = Counter(task.get("platform") for task in tasks if isinstance(task, dict))
        for platform in VIDEO_PLATFORMS:
            expect(task_counts[platform] >= 6, f"{platform} should have cover, storyboard, and B-roll tasks")

        task_types = Counter(task.get("asset_type") for task in tasks if isinstance(task, dict))
        for asset_type in ["cover_image", "storyboard_frame", "broll"]:
            expect(task_types[asset_type] > 0, f"asset tasks missing asset_type: {asset_type}")

        for task in tasks:
            expect(task.get("status") == "planned", f"task must remain planned: {task.get('task_id')}")
            expect(task.get("rights_status") == "pending_human_review", f"task rights must be pending: {task.get('task_id')}")
            expect(task.get("manual_review_required") is True, f"task must require manual review: {task.get('task_id')}")
            target_path = run_dir / str(task.get("target_path"))
            if task.get("asset_type") == "storyboard_frame":
                expect(target_path.exists(), f"storyboard frame should be generated by storyboard preview adapter: {task.get('target_path')}")
            if task.get("asset_type") == "broll":
                expect(not target_path.exists(), f"B-roll target should not be generated/imported yet: {task.get('target_path')}")

        media_manifest = load_json(run_dir / "assets/media_asset_manifest.json")
        expect(media_manifest.get("schema_version") == "phase4.media_asset_manifest.v1", "media manifest schema version mismatch")
        assets = media_manifest.get("assets", [])
        expect(len(assets) == len(tasks), "media manifest asset count must match task count")
        summary = media_manifest.get("summary", {})
        expect(summary.get("asset_count") == len(tasks), "media manifest summary asset_count mismatch")
        expect(summary.get("planned_count") == len(tasks), "media manifest summary planned_count mismatch")
        expect(summary.get("pending_rights_review_count") == len(tasks), "all media assets should await rights review")
        for asset in assets:
            expect(asset.get("status") == "planned", f"asset must remain planned: {asset.get('asset_id')}")
            expect(asset.get("rights_status") == "pending_human_review", f"asset rights must be pending: {asset.get('asset_id')}")
            expect(asset.get("manual_review_required") is True, f"asset must require manual review: {asset.get('asset_id')}")
            expect(asset.get("used_by"), f"asset must declare usage target: {asset.get('asset_id')}")

        ingest_guide = (run_dir / "assets/asset_ingest_guide.md").read_text(encoding="utf-8")
        for expected_text in ["The runner does not generate", "Planned Tasks", "Review required: true"]:
            expect(expected_text in ingest_guide, f"asset ingest guide missing text: {expected_text}")

        video_package = load_json(run_dir / "final/video_production_package.json")
        expect(video_package.get("asset_generation_tasks") == "assets/asset_generation_tasks.json", "video package missing asset tasks path")
        expect(video_package.get("media_asset_manifest") == "assets/media_asset_manifest.json", "video package missing media manifest path")
        for package in video_package.get("platform_packages", []):
            platform = package.get("platform")
            expect(len(package.get("asset_tasks", [])) == task_counts[platform], f"{platform} package asset_tasks mismatch")
            expect(len(package.get("media_assets", [])) == task_counts[platform], f"{platform} package media_assets mismatch")


def main() -> int:
    validate_workflow_outputs()
    print("Phase 4 asset drill passed: workflow outputs")
    validate_asset_pipeline_run()
    print("Phase 4 asset drill passed: task package and media manifest")
    print("Phase 4 asset pipeline validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
